import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { CKEditor } from "ckeditor4-react";

export default function Home() {
  const ckEditorConfig = {
    width: "80vw",
    height: "47vh",
  };
  // const ckEditorStyle = {};
  const message = "Past here";
  return (
    <div className={styles.container}>
      <Head>
        <title>Web text to markup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Paste Here</h1>
        <CKEditor
          config={ckEditorConfig}
          // style={ckEditorStyle}
          // initData={<p>Hello from CKEditor 4!</p>}
          onInstanceReady={() => {
            // console.log("Editor is ready!");
          }}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://susantpaudel.com.np"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/logo.png" alt="Techbizz Logo" width={80} height={80} />
          </span>
        </a>
      </footer>
    </div>
  );
}
